[package]

name = "http"
version = "0.0.0-prealpha"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-http.git"
description = "The future of the Rust HTTP stack."
readme = "README.md"
license = "MIT"

